# Generated by Django 3.2.12 on 2022-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, default='1981-10-10'),
            preserve_default=False,
        ),
    ]
